# Generated by Django 5.1 on 2025-11-22 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_donation_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='name',
        ),
    ]
