# Generated by Django 5.1 on 2025-12-08 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='transferred_to_creator',
            field=models.BooleanField(default=False),
        ),
    ]
