# Generated by Django 5.1 on 2025-12-09 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_donation_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'ordering': ['-date_donated']},
        ),
    ]
