# Generated by Django 5.1 on 2025-11-22 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaign_owner'),
        ('users', '0002_alter_child_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='owner',
        ),
        migrations.AddField(
            model_name='campaign',
            name='child',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owned_campaigns', to='users.child'),
            preserve_default=False,
        ),
    ]
