# Generated by Django 5.1 on 2025-11-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
