# Generated by Django 5.1 on 2026-02-15 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_initial'),
        ('campaigns', '0003_add_category_field'),
    ]

    operations = [
    ]
