# Generated by Django 5.1 on 2026-02-07 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_campaign_deadline_campaign_has_deadline_and_more'),
        ('users', '0002_child_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='users.child'),
        ),
    ]
