# Generated by Django 5.1 on 2026-02-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_merge_0002_initial_0003_add_category_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='category',
            field=models.CharField(choices=[('sports', 'Sports'), ('education', 'Education'), ('hobbies', 'Hobbies'), ('health', 'Health'), ('dreams', 'Dreams')], max_length=50),
        ),
    ]
