# Generated by Django 5.1 on 2025-12-08 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='pending_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
