# Generated by Django 5.1 on 2026-02-07 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('prefer not to say', 'Prefer not to say')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
