# Generated by Django 5.1 on 2025-12-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='stripe_onboarding_complete',
            field=models.BooleanField(default=False),
        ),
    ]
